# Generated by Django 5.0.7 on 2024-08-02 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.IntegerField(default=0)),
                ('branch', models.CharField(choices=[('Common', 'common/all'), ('CSE.', 'computer science and engg'), ('EC.', 'electronics and comm.'), ('Elec.', 'electrical'), ('IT.', 'information technology'), ('Mech.', 'mechanical'), ('Civil', 'civil'), ('AI.', 'Artificial Intelligence')], default='Common', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('revision', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_items', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.subject')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
