# Generated by Django 5.0.7 on 2024-08-03 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
